[package]
name = "todo"
version = "1.0.0"
authors = ["Max Wittig <max.wittig95@gmail.com>"]

[dependencies]
clap = "2.26.2"
serde = "1.0.16"
serde_yaml = "0.7.1"
serde_derive = "1.0.16"
prettytable-rs = "0.6.7"
chrono = "0.4.0"